name: geodesy_calc
description: Геодезический калькулятор для решения геодезических задач
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/background.png
    - assets/icon/cadas.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/cadas.png"
  adaptive_icon_background: "#121212"
  adaptive_icon_foreground: "assets/icon/cadas.png"
  min_sdk_android: 21